# Basic
title: WanLx
subtitle: A beautiful boy in the world
welcome_message: <a href="https://github.com/wanckl/wanckl.github.io" target="_blank">Download the site</a>
description: welcome to my personal page
# creator: <a href="http://onev.cat">@onevcat</a>

url: "http://github.com/wanckl"
header-img: assets/images/header.jpg

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://github.com/wanckl'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
#    weibo: wanckl
    github: wanckl
    twitter: wanckl
    linkin: WanL
#    gplus: 107108267983477358170
    mail: wanckl@foxmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
